from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

import pytest

from youdub.downloader import (
    DownloadConfig,
    download_url_to_artifacts,
    format_candidates,
    format_sort,
    supported_js_runtimes,
    ytdlp_base_options,
)
from youdub.locking import TaskLock, TaskLockBusy


class FakeYoutubeDL:
    calls: list[dict[str, Any]] = []
    download_attempts = 0
    unavailable_download_attempts = 0
    mutate_cookiefile = False
    staging_parent_path: Path | None = None
    preserved_staging_path: Path | None = None

    def __init__(self, params: dict[str, Any]):
        self.params = params
        FakeYoutubeDL.calls.append(params)

    def __enter__(self) -> "FakeYoutubeDL":
        return self

    def __exit__(self, *_: object) -> None:
        return None

    def extract_info(self, url: str, download: bool = False) -> dict[str, Any]:
        assert download is False
        self._mutate_cookiefile()
        return {
            "extractor_key": "Youtube",
            "id": "demo123",
            "title": "Demo Video",
            "uploader": "Demo Author",
            "upload_date": "20240601",
            "webpage_url": url,
        }

    def sanitize_info(self, info: dict[str, Any]) -> dict[str, Any]:
        return dict(info)

    def download(self, urls: list[str]) -> None:
        assert urls == ["https://example.test/watch?v=demo123"]
        self._mutate_cookiefile()
        FakeYoutubeDL.download_attempts += 1
        if FakeYoutubeDL.download_attempts <= FakeYoutubeDL.unavailable_download_attempts:
            raise RuntimeError("Requested format is not available")
        output_template = Path(self.params["outtmpl"])
        output_template.parent.mkdir(parents=True, exist_ok=True)
        if FakeYoutubeDL.staging_parent_path is None:
            FakeYoutubeDL.staging_parent_path = output_template.parent.parent
        assert output_template.parent.parent == FakeYoutubeDL.staging_parent_path
        assert output_template.parent.name.startswith(".download-staging-")
        assert output_template.parent.name != ".download-staging"
        if FakeYoutubeDL.preserved_staging_path is not None:
            assert FakeYoutubeDL.preserved_staging_path.exists()
        output_template.with_suffix(".mp4").write_bytes(b"video")
        output_template.with_suffix(".webp").write_bytes(b"cover")

    def _mutate_cookiefile(self) -> None:
        if not FakeYoutubeDL.mutate_cookiefile:
            return
        cookiefile = self.params.get("cookiefile")
        if cookiefile:
            Path(cookiefile).write_text("# This file is generated by yt-dlp.\n", encoding="utf-8")


@pytest.fixture(autouse=True)
def reset_fake_ytdl() -> None:
    supported_js_runtimes.cache_clear()
    FakeYoutubeDL.calls = []
    FakeYoutubeDL.download_attempts = 0
    FakeYoutubeDL.unavailable_download_attempts = 0
    FakeYoutubeDL.mutate_cookiefile = False
    FakeYoutubeDL.staging_parent_path = None
    FakeYoutubeDL.preserved_staging_path = None
    yield
    supported_js_runtimes.cache_clear()


def test_ytdlp_base_options_uses_nonempty_cookies_and_proxy(tmp_path: Path) -> None:
    supported_js_runtimes.cache_clear()
    cookies = tmp_path / "cookies.txt"
    cookies.write_text("# Netscape HTTP Cookie File\n", encoding="utf-8")

    options = ytdlp_base_options(DownloadConfig(cookies_path=cookies, proxy="http://127.0.0.1:7890"))

    assert options["cookiefile"] == str(cookies.resolve())
    assert options["proxy"] == "http://127.0.0.1:7890"
    assert options["remote_components"] == ["ejs:github"]
    assert options["extractor_args"] == {"youtube": {"player_js_variant": ["main"]}}


def test_ytdlp_base_options_ignores_empty_cookies(tmp_path: Path) -> None:
    cookies = tmp_path / "cookies.txt"
    cookies.write_text("", encoding="utf-8")

    options = ytdlp_base_options(DownloadConfig(cookies_path=cookies))

    assert "cookiefile" not in options


def test_supported_js_runtimes_prefers_supported_deno_and_ignores_old_node(monkeypatch) -> None:
    import youdub.downloader as downloader

    supported_js_runtimes.cache_clear()
    monkeypatch.setattr(downloader.shutil, "which", lambda name: f"/usr/bin/{name}" if name in {"deno", "node"} else None)

    def fake_run(args: list[str], **_: Any) -> subprocess.CompletedProcess[str]:
        output = {"deno": "deno 2.5.6\n", "node": "v20.20.2\n"}[Path(args[0]).name]
        return subprocess.CompletedProcess(args, 0, stdout=output, stderr="")

    monkeypatch.setattr(downloader.subprocess, "run", fake_run)

    assert supported_js_runtimes() == {"deno": {"path": "/usr/bin/deno"}}


def test_supported_js_runtimes_accepts_node_22(monkeypatch) -> None:
    import youdub.downloader as downloader

    supported_js_runtimes.cache_clear()
    monkeypatch.setattr(downloader.shutil, "which", lambda name: "/usr/local/bin/node" if name == "node" else None)
    monkeypatch.setattr(
        downloader.subprocess,
        "run",
        lambda args, **_: subprocess.CompletedProcess(args, 0, stdout="v22.16.0\n", stderr=""),
    )

    assert supported_js_runtimes() == {"node": {"path": "/usr/local/bin/node"}}


def test_format_candidates_uses_requested_height() -> None:
    assert format_candidates(720)[0] == (
        "bestvideo[ext=mp4][height<=720]+bestaudio[ext=m4a]/"
        "best[ext=mp4][height<=720]/best[height<=720]/best"
    )
    assert format_candidates(720)[-1] is None
    assert format_candidates(0)[0] == (
        "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
    )
    assert all(candidate is None or "height<=" not in candidate for candidate in format_candidates(0))
    assert format_sort(0) == ["ext:mp4:m4a"]
    assert format_sort(720) == ["res:720", "ext:mp4:m4a"]


def test_download_url_to_artifacts_writes_expected_files(tmp_path: Path) -> None:
    result = download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        tmp_path / "videos",
        DownloadConfig(youtube_dl_factory=FakeYoutubeDL),
    )

    assert result.media_path.name == "download.mp4"
    assert result.media_path.read_bytes() == b"video"
    assert result.cover_path is not None
    assert result.cover_path.name == "download.webp"
    assert result.source_key == "youtube:demo123"
    assert json.loads(result.info_path.read_text(encoding="utf-8"))["title"] == "Demo Video"
    assert result.task_dir == tmp_path / "videos" / "Demo Author" / "20240601 Demo Video"


def test_download_url_to_artifacts_skips_existing_media_without_force(tmp_path: Path) -> None:
    first = download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        tmp_path / "videos",
        DownloadConfig(youtube_dl_factory=FakeYoutubeDL),
    )
    first.media_path.write_bytes(b"existing")

    second = download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        tmp_path / "videos",
        DownloadConfig(youtube_dl_factory=FakeYoutubeDL),
    )

    assert second.media_path.read_bytes() == b"existing"
    assert FakeYoutubeDL.download_attempts == 1


def test_download_url_to_artifacts_refuses_locked_task(tmp_path: Path) -> None:
    task_dir = tmp_path / "videos" / "Demo Author" / "20240601 Demo Video"
    task_dir.mkdir(parents=True)

    with TaskLock(task_dir, "existing-download"):
        with pytest.raises(TaskLockBusy):
            download_url_to_artifacts(
                "https://example.test/watch?v=demo123",
                tmp_path / "videos",
                DownloadConfig(youtube_dl_factory=FakeYoutubeDL),
            )

    assert FakeYoutubeDL.download_attempts == 0


def test_download_url_to_artifacts_retries_format_candidates(tmp_path: Path) -> None:
    FakeYoutubeDL.unavailable_download_attempts = 1

    result = download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        tmp_path / "videos",
        DownloadConfig(youtube_dl_factory=FakeYoutubeDL),
    )

    download_calls = [call for call in FakeYoutubeDL.calls if "format" in call]
    assert result.media_path.read_bytes() == b"video"
    assert [call["format"] for call in download_calls[:2]] == [
        "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "bestvideo+bestaudio/best",
    ]
    assert all(call["format_sort"] == ["ext:mp4:m4a"] for call in download_calls[:2])


def test_download_url_to_artifacts_falls_back_to_default_format(tmp_path: Path) -> None:
    FakeYoutubeDL.unavailable_download_attempts = len(format_candidates(0)) - 1

    download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        tmp_path / "videos",
        DownloadConfig(youtube_dl_factory=FakeYoutubeDL),
    )

    download_calls = [call for call in FakeYoutubeDL.calls if "outtmpl" in call]
    assert "format" not in download_calls[-1]
    assert download_calls[-1]["format_sort"] == ["ext:mp4:m4a"]


def test_download_url_to_artifacts_uses_isolated_staging_dirs(tmp_path: Path) -> None:
    root = tmp_path / "videos"
    task_dir = root / "Demo Author" / "20240601 Demo Video"
    old_shared_staging = task_dir / ".download-staging"
    old_shared_staging.mkdir(parents=True)
    sentinel = old_shared_staging / "sentinel"
    sentinel.write_text("do not remove", encoding="utf-8")
    FakeYoutubeDL.preserved_staging_path = sentinel
    FakeYoutubeDL.unavailable_download_attempts = 1

    download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        root,
        DownloadConfig(youtube_dl_factory=FakeYoutubeDL),
    )

    download_calls = [call for call in FakeYoutubeDL.calls if "outtmpl" in call]
    staging_dirs = {Path(call["outtmpl"]).parent.name for call in download_calls}
    assert len(staging_dirs) == 2
    assert all(name.startswith(".download-staging-") for name in staging_dirs)
    assert old_shared_staging.exists()
    assert sentinel.read_text(encoding="utf-8") == "do not remove"
    assert not list(task_dir.glob(".download-staging-*"))


def test_download_url_to_artifacts_force_enables_overwrite(tmp_path: Path) -> None:
    download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        tmp_path / "videos",
        DownloadConfig(force=True, youtube_dl_factory=FakeYoutubeDL),
    )

    download_call = next(call for call in FakeYoutubeDL.calls if "format" in call)
    assert download_call["overwrites"] is True


def test_download_url_to_artifacts_does_not_let_ytdlp_mutate_original_cookies(tmp_path: Path) -> None:
    original_cookie_text = (
        "# Netscape HTTP Cookie File\n"
        ".youtube.com\tTRUE\t/\tTRUE\t1815872581\tLOGIN_INFO\tsecret\n"
    )
    cookies = tmp_path / "cookies.txt"
    cookies.write_text(original_cookie_text, encoding="utf-8")
    FakeYoutubeDL.mutate_cookiefile = True

    download_url_to_artifacts(
        "https://example.test/watch?v=demo123",
        tmp_path / "videos",
        DownloadConfig(cookies_path=cookies, youtube_dl_factory=FakeYoutubeDL),
    )

    assert cookies.read_text(encoding="utf-8") == original_cookie_text
    cookiefiles = {call["cookiefile"] for call in FakeYoutubeDL.calls if "cookiefile" in call}
    assert cookiefiles
    assert str(cookies.resolve()) not in cookiefiles
    assert all(not Path(cookiefile).exists() for cookiefile in cookiefiles)
