#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${YOUDUB_GPU_COMPOSE_FILE:-compose.gpu.yml}"
SERVICE="${YOUDUB_GPU_SERVICE:-youdub-gpu}"
SAMPLE_PATH="${1:-/data/samples/6o68Fg2-bhM.mp4}"
SAMPLE_INFO_PATH="${YOUDUB_SMOKE_INFO_PATH:-}"
SAMPLE_COVER_PATH="${YOUDUB_SMOKE_COVER_PATH:-}"
PROJECT_UID="$(stat -c '%u' .)"
PROJECT_GID="$(stat -c '%g' .)"
export YOUDUB_UID="${YOUDUB_UID:-$PROJECT_UID}"
export YOUDUB_GID="${YOUDUB_GID:-$PROJECT_GID}"
RUN_FLAGS=(--rm)

if [[ "${YOUDUB_GPU_TTY:-0}" != "1" ]]; then
  RUN_FLAGS+=(-T)
fi

if [[ $# -gt 3 ]]; then
  echo "usage: scripts/gpu_smoke.sh [/path/to/local-video.mp4] [/path/to/download.info.json] [/path/to/cover]" >&2
  exit 2
fi

if [[ $# -ge 2 ]]; then
  SAMPLE_INFO_PATH="$2"
fi
if [[ $# -ge 3 ]]; then
  SAMPLE_COVER_PATH="$3"
fi

mkdir -p \
  data/cache/huggingface \
  data/cache/nltk \
  data/cache/torch \
  data/config \
  data/cookies \
  data/logs \
  data/tasks \
  data/videos \
  models

echo "[gpu-smoke] compose_file=$COMPOSE_FILE service=$SERVICE uid=$YOUDUB_UID gid=$YOUDUB_GID"

if [[ "${YOUDUB_GPU_SKIP_BUILD:-0}" != "1" ]]; then
  echo "[gpu-smoke] building GPU image"
  docker compose -f "$COMPOSE_FILE" build
fi

echo "[gpu-smoke] running GPU dependency check"
docker compose -f "$COMPOSE_FILE" run "${RUN_FLAGS[@]}" "$SERVICE" \
  bash -lc 'echo "[gpu-smoke:container] check_gpu starting"; exec scripts/check_gpu.sh'

smoke_cmd=(scripts/smoke.sh "$SAMPLE_PATH")
if [[ -n "$SAMPLE_INFO_PATH" ]]; then
  smoke_cmd+=("$SAMPLE_INFO_PATH")
  if [[ -n "$SAMPLE_COVER_PATH" ]]; then
    smoke_cmd+=("$SAMPLE_COVER_PATH")
  fi
fi

echo "[gpu-smoke] running smoke pipeline: ${smoke_cmd[*]}"
docker compose -f "$COMPOSE_FILE" run "${RUN_FLAGS[@]}" \
  -e YOUDUB_SMOKE_SEPARATE=1 \
  -e YOUDUB_SMOKE_TRANSCRIBE="${YOUDUB_SMOKE_TRANSCRIBE:-0}" \
  -e YOUDUB_SMOKE_TRANSLATE="${YOUDUB_SMOKE_TRANSLATE:-0}" \
  -e YOUDUB_SMOKE_TTS="${YOUDUB_SMOKE_TTS:-0}" \
  -e YOUDUB_SMOKE_TRANSCRIBE_TTS="${YOUDUB_SMOKE_TRANSCRIBE_TTS:-0}" \
  -e YOUDUB_SMOKE_SUBTITLE="${YOUDUB_SMOKE_SUBTITLE:-0}" \
  -e YOUDUB_SMOKE_SYNTHESIZE="${YOUDUB_SMOKE_SYNTHESIZE:-0}" \
  -e YOUDUB_SMOKE_PREPARE_PUBLISH="${YOUDUB_SMOKE_PREPARE_PUBLISH:-0}" \
  -e YOUDUB_SMOKE_PUBLISH_BILIBILI="${YOUDUB_SMOKE_PUBLISH_BILIBILI:-0}" \
  -e NLTK_DATA="${NLTK_DATA:-/cache/nltk}" \
  -e YOUDUB_WHISPER_MODEL="${YOUDUB_WHISPER_MODEL:-large-v2}" \
  -e YOUDUB_WHISPER_DEVICE="${YOUDUB_WHISPER_DEVICE:-auto}" \
  -e YOUDUB_WHISPER_BATCH_SIZE="${YOUDUB_WHISPER_BATCH_SIZE:-32}" \
  -e YOUDUB_WHISPER_DIARIZATION="${YOUDUB_WHISPER_DIARIZATION:-1}" \
  -e YOUDUB_WHISPER_MIN_SPEAKERS="${YOUDUB_WHISPER_MIN_SPEAKERS:-}" \
  -e YOUDUB_WHISPER_MAX_SPEAKERS="${YOUDUB_WHISPER_MAX_SPEAKERS:-}" \
  -e YOUDUB_WHISPER_LANGUAGE="${YOUDUB_WHISPER_LANGUAGE:-}" \
  -e YOUDUB_WHISPER_INITIAL_PROMPT="${YOUDUB_WHISPER_INITIAL_PROMPT:-}" \
  -e YOUDUB_TTS_ASR_LANGUAGE="${YOUDUB_TTS_ASR_LANGUAGE:-zh}" \
  -e YOUDUB_TTS_ASR_INITIAL_PROMPT="${YOUDUB_TTS_ASR_INITIAL_PROMPT:-以下是普通话的句子。}" \
  -e YOUDUB_TRANSLATION_LANGUAGE="${YOUDUB_TRANSLATION_LANGUAGE:-简体中文}" \
  -e YOUDUB_TRANSLATION_BATCH_SIZE="${YOUDUB_TRANSLATION_BATCH_SIZE:-20}" \
  -e YOUDUB_TRANSLATION_MAX_RETRIES="${YOUDUB_TRANSLATION_MAX_RETRIES:-4}" \
  -e YOUDUB_TRANSLATION_RETRY_BACKOFF_SECONDS="${YOUDUB_TRANSLATION_RETRY_BACKOFF_SECONDS:-1}" \
  -e YOUDUB_TRANSLATION_RETRY_BACKOFF_MULTIPLIER="${YOUDUB_TRANSLATION_RETRY_BACKOFF_MULTIPLIER:-2}" \
  -e YOUDUB_TRANSLATION_RETRY_MAX_BACKOFF_SECONDS="${YOUDUB_TRANSLATION_RETRY_MAX_BACKOFF_SECONDS:-8}" \
  -e YOUDUB_TRANSLATION_FORCE_JSON_OUTPUT="${YOUDUB_TRANSLATION_FORCE_JSON_OUTPUT:-1}" \
  -e YOUDUB_TRANSLATION_TEMPERATURE="${YOUDUB_TRANSLATION_TEMPERATURE:-0}" \
  -e YOUDUB_TRANSLATION_EXTRA_PROMPT="${YOUDUB_TRANSLATION_EXTRA_PROMPT:-}" \
  -e YOUDUB_TRANSLATION_SUMMARY_EXTRA_PROMPT="${YOUDUB_TRANSLATION_SUMMARY_EXTRA_PROMPT:-}" \
  -e YOUDUB_TRANSLATION_CONTEXT_EXTRA_PROMPT="${YOUDUB_TRANSLATION_CONTEXT_EXTRA_PROMPT:-}" \
  -e YOUDUB_TRANSLATION_SEGMENT_EXTRA_PROMPT="${YOUDUB_TRANSLATION_SEGMENT_EXTRA_PROMPT:-}" \
  -e YOUDUB_TRANSLATION_CORRECTION_PROMPT="${YOUDUB_TRANSLATION_CORRECTION_PROMPT:-}" \
  -e YOUDUB_COOKIES_PATH="${YOUDUB_COOKIES_PATH:-/data/cookies/cookies.txt}" \
  -e YOUDUB_YTDLP_PROXY="${YOUDUB_YTDLP_PROXY:-}" \
  -e YOUDUB_DOWNLOAD_MAX_HEIGHT="${YOUDUB_DOWNLOAD_MAX_HEIGHT:-}" \
  -e YOUDUB_TTS_MODEL="${YOUDUB_TTS_MODEL:-openbmb/VoxCPM2}" \
  -e YOUDUB_TTS_MODEL_DIR="${YOUDUB_TTS_MODEL_DIR:-}" \
  -e YOUDUB_TTS_LOAD_DENOISER="${YOUDUB_TTS_LOAD_DENOISER:-0}" \
  -e YOUDUB_TTS_CFG_VALUE="${YOUDUB_TTS_CFG_VALUE:-2.0}" \
  -e YOUDUB_TTS_INFERENCE_TIMESTEPS="${YOUDUB_TTS_INFERENCE_TIMESTEPS:-10}" \
  -e YOUDUB_TTS_MIN_REFERENCE_MS="${YOUDUB_TTS_MIN_REFERENCE_MS:-1200}" \
  -e YOUDUB_TTS_ALIGN_AUDIO="${YOUDUB_TTS_ALIGN_AUDIO:-1}" \
  -e YOUDUB_TTS_STRETCH_BASE_MIN="${YOUDUB_TTS_STRETCH_BASE_MIN:-0.8}" \
  -e YOUDUB_TTS_STRETCH_BASE_MAX="${YOUDUB_TTS_STRETCH_BASE_MAX:-1.2}" \
  -e YOUDUB_TTS_STRETCH_LOCAL_MIN="${YOUDUB_TTS_STRETCH_LOCAL_MIN:-0.9}" \
  -e YOUDUB_TTS_STRETCH_LOCAL_MAX="${YOUDUB_TTS_STRETCH_LOCAL_MAX:-1.1}" \
  -e YOUDUB_BURN_SUBTITLES="${YOUDUB_BURN_SUBTITLES:-1}" \
  -e YOUDUB_SYNTHESIS_TTS_VOLUME="${YOUDUB_SYNTHESIS_TTS_VOLUME:-1.0}" \
  -e YOUDUB_SYNTHESIS_INSTRUMENTS_VOLUME="${YOUDUB_SYNTHESIS_INSTRUMENTS_VOLUME:-0.30}" \
  -e YOUDUB_SYNTHESIS_PRESET="${YOUDUB_SYNTHESIS_PRESET:-fast}" \
  -e YOUDUB_SYNTHESIS_CRF="${YOUDUB_SYNTHESIS_CRF:-23}" \
  -e YOUDUB_SUBTITLE_LANGUAGE="${YOUDUB_SUBTITLE_LANGUAGE:-zh}" \
  -e YOUDUB_SUBTITLE_FONT="${YOUDUB_SUBTITLE_FONT:-}" \
  -e YOUDUB_PUBLISH_TITLE_MAX_CHARS="${YOUDUB_PUBLISH_TITLE_MAX_CHARS:-80}" \
  -e YOUDUB_PUBLISH_MAX_TAGS="${YOUDUB_PUBLISH_MAX_TAGS:-10}" \
  -e YOUDUB_PUBLISH_MAX_TAG_CHARS="${YOUDUB_PUBLISH_MAX_TAG_CHARS:-20}" \
  -e YOUDUB_PUBLISH_DRY_RUN="${YOUDUB_PUBLISH_DRY_RUN:-0}" \
  -e YOUDUB_PUBLISH_FORCE="${YOUDUB_PUBLISH_FORCE:-0}" \
  -e YOUDUB_PUBLISH_CONFIRM="${YOUDUB_PUBLISH_CONFIRM:-0}" \
  -e BILI_TID="${BILI_TID:-201}" \
  -e BILI_ORIGINAL="${BILI_ORIGINAL:-0}" \
  -e BILI_SOURCE="${BILI_SOURCE:-}" \
  -e BILI_WATERMARK="${BILI_WATERMARK:-1}" \
  -e BILI_SESSDATA="${BILI_SESSDATA:-}" \
  -e BILI_BILI_JCT="${BILI_BILI_JCT:-}" \
  -e HF_READ_TOKEN="${HF_READ_TOKEN:-}" \
  -e OPENAI_API_KEY="${OPENAI_API_KEY:-}" \
  -e OPENAI_BASE_URL="${OPENAI_BASE_URL:-}" \
  -e OPENAI_API_BASE="${OPENAI_API_BASE:-}" \
  -e OPENAI_MODEL="${OPENAI_MODEL:-}" \
  -e MODEL_NAME="${MODEL_NAME:-}" \
  "$SERVICE" \
  bash -lc 'echo "[gpu-smoke:container] smoke starting: $*"; exec "$@"' \
  bash \
  "${smoke_cmd[@]}"
